### ISSUE TITLE
Error when starting the environment

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee-factory#16]
When starting the environment I got an error. It seems that returned value for the check was not a valid JSON and it got stuck in that state.

```
% ./scripts/environment.sh start
Create Docker network...
Start Blockchain node...
b322626d20ce
Start Bee nodes...
34d93cf62eed
b94088d29547
ae540643bfb0
f606889e7700
5776154b57a6
Check whether the queen node has been connected to every worker...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Only  peers have been connected to the Queen Bee node yet. Waiting until 4
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Only  peers have been connected to the Queen Bee node yet. Waiting until 4
```

**Comment by nugaon** [comment]
please run `environment.sh stop` and `bee-cleanup.sh` scripts and try it again.

**Comment by agazso** [comment]
So I just stopped with Ctrl-C and started it again and it worked.
