### ISSUE TITLE
Only 0 peers have been connected to the Queen Bee node yet. Waiting until 4

### ISSUE THREAD

**Issue by EysaDun** [ethersphere/bee-factory#50]
```
eysir@eysir-ubu:~/workspace/golang/bee-factory$ ./scripts/bee.sh start --workers=4
start Bee Queen process
5c45909d0c6ac1d6a718372d792e23d1bbe239f343b66e3f227d2cced33cebec
No JSON object could be decoded
Waiting for the Queen initialization...
Waiting for the Queen initialization...
Waiting for the Queen initialization...
Waiting for the Queen initialization...
Waiting for the Queen initialization...
Waiting for the Queen initialization...
Waiting for the Queen initialization...
Waiting for the Queen initialization...
Queen underlay address: /ip4/172.19.0.3/tcp/1634/p2p/16Uiu2HAmBTraFFjULgNxfUm4DbCjuejN8KFhx9xAdE4kKRt82ccL
start Bee worker 1 process
f48aac36e34095e0be50b102ae08625c64120ff7ceb4cc1f5aaa8d4335be59fc
start Bee worker 2 process
51b586fc3032a937c3f98e9db8f788b22f351f5417b070e53f84fd47e9b53f3c
start Bee worker 3 process
5d9077964c609efc2bebb8e551b4ad345fcd4ab4ca2eaaf9cf38cacbf262216d
start Bee worker 4 process
42ae16419f998539299dc512ff56fcbb06d16532f2d88d7af0ed3dd679fdefc0
Check whether the queen node has been connected to every worker...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: object of type 'NoneType' has no len()
Only 0 peers have been connected to the Queen Bee node yet. Waiting until 4
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: object of type 'NoneType' has no len()
Only 0 peers have been connected to the Queen Bee node yet. Waiting until 4
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: object of type 'NoneType' has no len()
Only 0 peers have been connected to the Queen Bee node yet. Waiting until 4
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: object of type 'NoneType' has no len()
Only 0 peers have been connected to the Queen Bee node yet. Waiting until 4
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: object of type 'NoneType' has no len()
Only 0 peers have been connected to the Queen Bee node yet. Waiting until 4

```
And, what's wrong?

**Comment by nugaon** [comment]
there are some errors on polling at the start but after a while all nodes should be connected to the queen node.
