### ISSUE TITLE
contracts do not compile on mac m1

### ISSUE THREAD

**Issue by significance** [ethersphere/bee-factory#80]
```
sig :: Code/swarm/bee-factory » npm run migrate:contracts
...
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
> Artifacts written to /Users/sig32/Code/swarm/bee-factory/build/contracts
> Compiled successfully using:
   - solc: 0.6.12+commit.27d51765.Linux.g++

TypeError: Db.connect is not a function
    at Object.save (/Users/sig32/Code/swarm/bee-factory/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:115:1)
    at Object.compileAndSave (/Users/sig32/Code/swarm/bee-factory/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:100:1)
    at Object.run (/Users/sig32/Code/swarm/bee-factory/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:199:1)
    at Command.run (/Users/sig32/Code/swarm/bee-factory/node_modules/truffle/build/webpack:/packages/core/lib/command.js:147:1)
Truffle v5.3.6 (core: 5.3.6)
Node v16.14.0
```

**Comment by AuHau** [comment]
Thanks for the report, but generally unless you need some super special usecase, it is not needed to build your own images of Bee Factory and you can instead use those that are automatically build by CI. I am in process of rewriting the orchestration part into proper TS CLI.

Till then you can run built images by setting this env. variables:
```
export BEE_VERSION="1.5.0-dda5606e-stateful"
export BLOCKCHAIN_VERSION="1.2.0-for-$BEE_VERSION"
export BEE_ENV_PREFIX="swarm-test"
export BEE_IMAGE_PREFIX="docker.pkg.github.com/ethersphere/bee-factory"
export COMMIT_VERSION_TAG="false"
```

Logging into Docker PKG repository (`docker login https://docker.pkg.github.com` with your username and a PAT) and then running `./scripts/environment.sh start --ephemeral`

**Comment by AuHau** [comment]
This should be fixed, but from now on building your own images is not really recommended and it is recommended to use already prebuild images.
